package org.sinhala.wordnet.wordnetDB.model;

public enum MongoSinhalaPointerTyps {

	ANTONYM,HYPERNYM,HYPONYM,ENTAILMENT,SIMILAR_TO,MEMBER_HOLONYM,SUBSTANCE_HOLONYM,PART_HOLONYM,MEMBER_MERONYM,SUBSTANCE_MERONYM,
	PART_MERONYM,CAUSE,PARTICIPLE_OF,SEE_ALSO,PERTAINYM,ATTRIBUTE,VERB_GROUP,DERIVATION,DOMAIN_ALL,MEMBER_ALL,CATEGORY,USAGE,
	REGION,CATEGORY_MEMBER,USAGE_MEMBER,REGION_MEMBER,INSTANCE_HYPERNYM,INSTANCES_HYPONYM,DERIVATION_TYPE,ROOT,ORIGIN,
}
